const seneca = require('seneca')()

seneca
    .client({
        type: 'http',
        port: '8000',
        host: 'localhost',
    })
    .ready(function() {
        seneca.act({
            role: 'aws',
            service: 'S3',
            cmd: 'putObject',
            params: {
                Bucket: /* Paste in your Bucket name */,
                Key: 'seneca-aws-adapter-test.txt',
                Body: 'This data is generated by seneca-aws-adapter S3 example.'
            }
        }, function(error, result) {
            if (error) {
                seneca.log.error(error)
                return seneca.log.error(error)
            }

            seneca.log.info(result)
        })
    })
