const seneca = require('seneca')()

seneca
    .client({
        type: 'http',
        port: '8000',
        host: 'localhost',
    })
    .ready(function() {
        // Sync
        seneca.act({
            role: 'aws',
            service: 'S3',
            cmd: 'putObject',
            params: {
                Bucket: process.env.S3_TEST_BUCKET,
                Key: 'seneca-aws-adapter-test.txt',
                Body: 'This data is generated by seneca-aws-adapter S3 example.'
            }
        }, function(error, result) {
            if (error) {
                seneca.log.error(error)
                return seneca.log.error(error)
            }

            seneca.log.info(result)
        })

        // Async
        seneca.act({
            role: 'aws',
            service: 'S3',
            cmd: 'putObject',
            params: {
                Bucket: process.env.S3_TEST_BUCKET,
                Key: 'seneca-aws-adapter-async-test.txt',
                Body: 'This data is generated by seneca-aws-adapter asynchronous S3 example.'
            },
            eventListeners: {
                success: function(resp) {
                    seneca.log.info(resp)
                },
                error: function(err) {
                    seneca.log.error(err)
                }
            }
        }, function(error, result) {
            if (error) {
                seneca.log.error(error)
                return seneca.log.error(error)
            }

            seneca.log.info(result)
        })
    })
